name: Deploy - UI Storybook

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout
       uses: actions/checkout@v4

     - name: Setup Node.js
       uses: actions/setup-node@v4
       with:
          node-version: '20.x'

    - name: Build Storybook
       uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
       with:
          install_command: npm ci
          build_command: npm run build-storybook
          path: storybook-static
          checkout: false