name: Deploy - UI Storybook

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v4

     - name: Setup Node.js
       uses: actions/setup-node@v4
       with:
          node-version: '20.x'

     - name: Build Storybook
       env: 
         TURBO_TOKEN:EIeM8IMtp9GBe5SCwpR4TNFB 
         TURBO_TEAM:dafaz
       uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
       with:
          install_command: npm ci
          build_command: npm run build 
          path: ./packages/docs/storybook-static
          checkout: false